/* ==========================================================================
   MFC — DONNÉES DU MENU
   Source de vérité : menu réel MFC (capture d'écran fournie par le client).
   Ne pas inventer de produits, prix, descriptions ou ingrédients.
   Structure volontairement simple pour être modifiée facilement plus tard.

   Champs par produit :
   - id            : identifiant unique (slug)
   - category      : 'twister-burgers' | 'box' | 'big-box' | 'sides'
   - name          : nom du produit (tel quel dans le menu original)
   - description   : texte descriptif si présent dans le menu original (sinon null)
   - ingredients   : liste du contenu si présent dans le menu original (sinon null)
   - price         : prix de base en DH (nombre)
   - priceLabel    : affichage du prix tel qu'imprimé ("150 DH", etc.)
   - options       : variantes de prix ("Seul" / "Menu") si présentes, sinon null
   - people        : nombre de personnes si indiqué ("2 Personnes"...), sinon null
   - image         : chemin vers la photo issue du menu original
   - badge         : badge éventuel du menu original (aucun trouvé actuellement)
   - needsReview   : true si une valeur du menu original était partiellement
                      illisible/coupée sur la capture fournie (voir note en fin de fichier)
   ========================================================================== */

const MFC_CATEGORIES = [
  {
    id: 'twister-burgers',
    label: 'Twister & Burgers',
    tagline: 'Croustillant. Généreux. Signature.',
  },
  {
    id: 'box',
    label: 'Box',
    tagline: 'Le repas complet, prêt à partager.',
  },
  {
    id: 'big-box',
    label: 'Big Box',
    tagline: 'Pour les grandes tablées et les grandes faims.',
  },
  {
    id: 'sides',
    label: 'Sides',
    tagline: 'Les accompagnements qui font la différence.',
  },
];

const MFC_PRODUCTS = [
  /* ---------------------- TWISTER & BURGERS ---------------------- */
  {
    id: 'regime',
    category: 'twister-burgers',
    name: 'Régime',
    description: null,
    ingredients: null,
    price: 35,
    priceLabel: '35 DH',
    options: [
      { name: 'Seul', price: 35 },
      { name: 'Menu', price: 42 },
    ],
    people: null,
    image: 'images/menu/twister-burgers/regime.jpg',
    badge: null,
  },
  {
    id: 'complet',
    category: 'twister-burgers',
    name: 'Complet',
    description: null,
    ingredients: null,
    price: 58,
    priceLabel: '58 DH',
    options: [
      { name: 'Seul', price: 58 },
      { name: 'Menu', price: 74 },
    ],
    people: null,
    image: 'images/menu/twister-burgers/complet.jpg',
    badge: null,
  },
  {
    id: 'cadeau',
    category: 'twister-burgers',
    name: 'Cadeau',
    description: null,
    ingredients: null,
    price: 55,
    priceLabel: '55 DH',
    options: [
      { name: 'Seul', price: 55 },
      { name: 'Menu', price: 68 },
    ],
    people: null,
    image: 'images/menu/twister-burgers/cadeau.jpg',
    badge: null,
  },
  {
    id: 'le-crispy',
    category: 'twister-burgers',
    name: 'Le Crispy',
    description: null,
    ingredients: null,
    price: 38,
    priceLabel: '38 DH',
    options: [
      { name: 'Seul', price: 38 },
      { name: 'Menu', price: 45 },
    ],
    people: null,
    image: 'images/menu/twister-burgers/crispy.jpg',
    badge: null,
  },
  {
    id: 'le-crunchy',
    category: 'twister-burgers',
    name: 'Le Crunchy',
    description: null,
    ingredients: null,
    price: 40,
    priceLabel: '40 DH',
    options: [
      { name: 'Seul', price: 40 },
      { name: 'Menu', price: 55 },
    ],
    people: null,
    image: 'images/menu/twister-burgers/crunchy.jpg',
    badge: null,
  },
  {
    id: 'mfc-wrap',
    category: 'twister-burgers',
    name: 'MFC Wrap',
    description: null,
    ingredients: null,
    price: 35,
    priceLabel: '35 DH',
    options: [
      { name: 'Seul', price: 35 },
      { name: 'Menu', price: 42 },
    ],
    people: null,
    image: 'images/menu/twister-burgers/wrap.jpg',
    badge: null,
  },

  /* ------------------------------- BOX ---------------------------- */
  {
    id: 'rapide',
    category: 'box',
    name: 'Rapide',
    description: null,
    ingredients: null,
    price: 35,
    priceLabel: '35 DH',
    options: [
      { name: 'Seul', price: 35 },
      { name: 'Menu', price: 42 },
    ],
    people: null,
    image: 'images/menu/twister-burgers/rapide.jpg',
    badge: null,
  },
  {
    id: 'le-chef',
    category: 'box',
    name: 'Le Chef',
    description: null,
    ingredients: null,
    price: 60,
    priceLabel: '60 DH',
    options: [
      { name: 'Seul', price: 60 },
      { name: 'Menu', price: 70 },
    ],
    people: null,
    image: 'images/menu/twister-burgers/chef.jpg',
    badge: null,
  },
  {
    id: 'croustillant',
    category: 'box',
    name: 'Croustillant',
    description: null,
    ingredients: null,
    price: 40,
    priceLabel: '40 DH',
    options: [
      { name: 'Seul', price: 40 },
      { name: 'Menu', price: 55 },
    ],
    people: null,
    image: 'images/menu/twister-burgers/croustillant.jpg',
    badge: null,
  },
  {
    id: 'le-partager',
    category: 'box',
    name: 'Le Partager',
    description: null,
    ingredients: null,
    price: 60,
    priceLabel: '60 DH',
    options: [
      { name: 'Seul', price: 60 },
      { name: 'Menu', price: 70 },
    ],
    people: null,
    image: 'images/menu/twister-burgers/partager.jpg',
    badge: null,
  },

  /* ----------------------------- BIG BOX --------------------------- */
  {
    id: 'duo',
    category: 'big-box',
    name: 'Duo',
    description: null,
    ingredients: ['8 Pièces chicken', '2 Frites', '4 Buns', '2 Riz Chili', '1L Boisson'],
    price: 150,
    priceLabel: '150 DH',
    options: null,
    people: '2 Personnes',
    image: 'images/menu/big-box/family-bucket-large.jpg',
    badge: null,
  },
  {
    id: 'ensemble',
    category: 'big-box',
    name: 'Ensemble',
    description: null,
    ingredients: ['12 Pièces chicken', '4 Frites', '8 Buns', '4 Riz Chili', '1L Boisson'],
    price: 280,
    priceLabel: '280 DH',
    options: null,
    people: '4 Personnes',
    image: 'images/menu/big-box/family-bucket-large.jpg',
    badge: null,
  },
  {
    id: 'fidelity',
    category: 'big-box',
    name: 'Fidelity',
    description: null,
    ingredients: ['10 Pièces chicken', '3 Frites', '6 Buns', '3 Riz Chili', '1L Boisson'],
    price: 200,
    priceLabel: '200 DH',
    options: null,
    people: '3 Personnes',
    image: 'images/menu/big-box/family-bucket-large.jpg',
    badge: null,
  },
  {
    id: 'special',
    category: 'big-box',
    name: 'Special',
    description: null,
    ingredients: ['6 Pièces chicken', '4 Fillets', '4 Pains', '4 Sauces'],
    price: 100,
    priceLabel: '100 DH',
    options: null,
    people: null,
    image: 'images/menu/big-box/family-bucket-large.jpg',
    badge: null,
  },

  /* ------------------------------ SIDES ----------------------------- */
  {
    id: '3-strips',
    category: 'sides',
    name: '3 Strips',
    description: null,
    ingredients: null,
    price: 30,
    priceLabel: '30 DH',
    options: null,
    people: null,
    image: 'images/menu/sides/strips.jpg',
    badge: null,
  },
  {
    id: 'piece-chicken',
    category: 'sides',
    name: 'Pièce Chicken',
    description: null,
    ingredients: null,
    price: 15,
    priceLabel: '15 DH',
    options: null,
    people: null,
    image: 'images/menu/sides/piece-chicken.jpg',
    badge: null,
  },
  {
    id: 'riz',
    category: 'sides',
    name: 'Riz',
    description: null,
    ingredients: null,
    price: 20,
    priceLabel: '20 DH',
    options: null,
    people: null,
    image: 'images/menu/sides/riz.jpg',
    badge: null,
  },
  {
    id: 'salade-mfc',
    category: 'sides',
    name: 'Salade MFC',
    description: null,
    ingredients: null,
    price: 30,
    priceLabel: '30 DH',
    options: null,
    people: null,
    image: 'images/menu/sides/salade.jpg',
    badge: null,
  },
  {
    id: '6-pieces-nuggets',
    category: 'sides',
    name: '6 Pièces Nuggets',
    description: null,
    ingredients: null,
    price: 25,
    priceLabel: '25 DH',
    options: null,
    people: null,
    image: 'images/menu/sides/nuggets.jpg',
    badge: null,
  },
  {
    id: '6-wings',
    category: 'sides',
    name: '6 Wings',
    description: null,
    ingredients: null,
    price: 30,
    priceLabel: '30 DH',
    options: null,
    people: null,
    image: 'images/menu/sides/wings.jpg',
    badge: null,
  },
  {
    id: '6-croquettes',
    category: 'sides',
    name: '6 Croquettes',
    description: null,
    ingredients: null,
    price: 25,
    priceLabel: '25 DH',
    options: null,
    people: null,
    image: 'images/menu/sides/croquettes.jpg',
    badge: null,
  },
  {
    id: 'corn',
    category: 'sides',
    name: 'Corn',
    description: null,
    ingredients: null,
    price: 30,
    priceLabel: '30 DH',
    options: null,
    people: null,
    image: 'images/menu/sides/corn.jpg',
    badge: null,
  },
  {
    id: 'frites',
    category: 'sides',
    name: 'Frites',
    description: null,
    ingredients: null,
    price: 12,
    priceLabel: '12 DH',
    options: null,
    people: null,
    image: 'images/menu/sides/frites.jpg',
    badge: null,
  },
  {
    id: 'mfc-mix',
    category: 'sides',
    name: 'MFC Mix',
    description: null,
    ingredients: null,
    price: 30,
    priceLabel: '30 DH',
    options: null,
    people: null,
    image: 'images/menu/sides/mfc-mix.jpg',
    badge: null,
  },
  {
    id: 'fried-cheese',
    category: 'sides',
    name: 'Fried Cheese',
    description: null,
    ingredients: null,
    price: 20,
    priceLabel: '20 DH',
    options: null,
    people: null,
    image: 'images/menu/sides/fried-cheese.jpg',
    badge: null,
  },
  {
    id: 'tiramisu',
    category: 'sides',
    name: 'Tiramisu',
    description: null,
    ingredients: null,
    price: 25,
    priceLabel: '25 DH',
    options: null,
    people: null,
    image: 'images/menu/sides/tiramisu.jpg',
    badge: null,
  },
];

/* Coordonnées de commande — reprises du menu original (bouton "ORDER NOW"). */
const MFC_ORDER_PHONE = '0528236023';

/* NOTE — les prix "Croustillant" et "Le Partager" (partiellement masqués sur
   une première capture) ont été confirmés via une capture du menu officiel
   et sont maintenant renseignés ci-dessus. */
